<a href="https://colab.research.google.com/github/nguyenminhkhuong/machine_learning/blob/main/NumPyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
random = np.random.randint(low=10, high=101, size=10)
print(random)

[56 92 91 94 50 89 13 60 77 99]


In [ ]:
random_float = np.random.random(10)
print(random_float)

[0.73550512 0.69570613 0.31637639 0.01127685 0.17119098 0.37038171
 0.20515553 0.0218304  0.53295598 0.88214199]


In [ ]:
feature = np.arange(6, 21)
label = 3 * feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = np.random.random([15]) * 4 - 2
print(noise)
label = label + noise
print(label)

[ 1.34026305  0.25436889  1.97824749 -1.92873744  0.2748544  -1.15825432
  1.85104156  1.10895458 -0.69851311  0.8381243   1.62234023 -0.93195693
  1.28593326 -1.09764163 -1.53543933]
[24.33186343 26.88454521 30.25561797 29.7963846  34.48439335 35.14386975
 41.10012693 42.82131574 45.05199546 48.0300358  53.11771401 53.46163064
 57.53394238 58.3573197  63.28322917]
